---
- name: playbook to ensure pmlogger is archiving lmsensors metrics
  hosts: all
  gather_facts: yes
  become: true
  remote_user: chris

  tasks:
    - name: Ensure controlfile is in place
      copy:
        src: files/lmsensors
        dest: /etc/pcp/pmlogger/control.d/lmsensors
      notify: pmlogger restart

    - name: Ensure pmlogger conffile is in place
      copy:
        src: files/config.lmsensors
        dest: /var/lib/pcp/config/pmlogger/config.lmsensors
      notify: pmlogger restart

  handlers:
    - name: pmlogger restart
      shell:
        cmd: systemctl restart pmlogger

#    - name: debug
#      debug:
#        var: ansible_facts
